# Generated by Django 4.1.7 on 2023-02-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название группы"),
                ),
                ("description", models.TextField(blank=True, max_length=600)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
