# Generated by Django 4.1.7 on 2023-02-28 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_alter_group_options_usergrouprelation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usergrouprelation",
            options={
                "ordering": ["id"],
                "verbose_name": "Связь пользователя и группы",
                "verbose_name_plural": "Связи пользователей и групп",
            },
        ),
        migrations.AlterField(
            model_name="group",
            name="date_created",
            field=models.DateField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True, max_length=600, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активность"),
        ),
        migrations.AlterField(
            model_name="group",
            name="user_created",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель группы",
            ),
        ),
        migrations.AlterField(
            model_name="usergrouprelation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="",
            ),
        ),
    ]
