# Generated by Django 4.1.7 on 2023-02-28 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_usergrouprelation_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneyFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=19, verbose_name="Сумма"
                    ),
                ),
                (
                    "comment",
                    models.TextField(max_length=500, verbose_name="Комментарий"),
                ),
                ("date", models.DateField(verbose_name="Дата поступления")),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.budget",
                        verbose_name="Бюджет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение денег",
                "verbose_name_plural": "Движения денег",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MoneyFlowCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Наименование")),
            ],
            options={
                "verbose_name": "Категория движения денег",
                "verbose_name_plural": "Категории движения денег",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MoneyFlowSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_created=True, verbose_name="Время создания"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "moneyflow_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.moneyflowcategory",
                        verbose_name="Категория движения денег",
                    ),
                ),
                (
                    "user_created",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория движения денег",
                "verbose_name_plural": "Подкатегории движения денег",
                "ordering": ["id"],
            },
        ),
        migrations.RemoveField(
            model_name="incomecategory",
            name="group",
        ),
        migrations.RemoveField(
            model_name="incomecategory",
            name="user_created",
        ),
        migrations.RemoveField(
            model_name="outgo",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="outgo",
            name="category",
        ),
        migrations.RemoveField(
            model_name="outgo",
            name="user_added",
        ),
        migrations.RemoveField(
            model_name="outgocategory",
            name="group",
        ),
        migrations.RemoveField(
            model_name="outgocategory",
            name="user_created",
        ),
        migrations.DeleteModel(
            name="Income",
        ),
        migrations.DeleteModel(
            name="IncomeCategory",
        ),
        migrations.DeleteModel(
            name="Outgo",
        ),
        migrations.DeleteModel(
            name="OutgoCategory",
        ),
        migrations.AddField(
            model_name="moneyflow",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.moneyflowcategory",
                verbose_name="Доход или расход",
            ),
        ),
        migrations.AddField(
            model_name="moneyflow",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="finance.moneyflowsubcategory",
                verbose_name="Категория доходов",
            ),
        ),
        migrations.AddField(
            model_name="moneyflow",
            name="user_added",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
