# Generated by Django 4.1.7 on 2023-02-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productsinlist",
            options={
                "ordering": ["id"],
                "verbose_name": "Продукт в списке",
                "verbose_name_plural": "Продукты в списке",
            },
        ),
        migrations.AddField(
            model_name="productsinlist",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Количество"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productsinlist",
            name="measure",
            field=models.TextField(
                default=1, max_length=20, verbose_name="Мера измерения"
            ),
            preserve_default=False,
        ),
    ]
