# Generated by Django 4.1.7 on 2023-02-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_usergrouprelation_options_and_more"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.group",
                verbose_name="Группа",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.group",
                verbose_name="Группа",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subtask",
            name="description",
            field=models.TextField(blank=True, max_length=500, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="is_done",
            field=models.BooleanField(default=False, verbose_name="Выполнено"),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(default=False, verbose_name="Выполнено"),
        ),
    ]
