# Generated by Django 4.1.7 on 2023-03-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="image",
        ),
    ]
