# Generated by Django 4.1.7 on 2023-02-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_responsibleontask"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Изображение"
            ),
        ),
    ]
